/* LinguaLoop — Dữ liệu mẫu dùng chung cho tất cả trang Giảng viên */
'use strict';
const DATA = {
  topLessons: [
    { title:'Ordering Coffee at Starbucks', cefr:'A2', views:312, dictAvg:78, shadowAvg:72 },
    { title:'Airport Check-in Conversation', cefr:'B1', views:287, dictAvg:71, shadowAvg:68 },
    { title:'Job Interview: Tell Me About Yourself', cefr:'B2', views:241, dictAvg:65, shadowAvg:61 },
    { title:'Talking About the Weather', cefr:'A1', views:198, dictAvg:84, shadowAvg:80 },
    { title:'Ordering Food at a Restaurant', cefr:'A2', views:175, dictAvg:76, shadowAvg:70 },
  ],
  hardSents: [
    { text:"I think this is the third time I've been here.", lesson:'Airport Check-in', attempts:89, avg:42 },
    { text:"Could you please speak a little more slowly?", lesson:'Everyday Conversation', attempts:76, avg:48 },
    { text:"The weather has been particularly unpleasant lately.", lesson:'Weather Talk', attempts:64, avg:51 },
    { text:"I'd like to make a reservation for two, please.", lesson:'At the Restaurant', attempts:58, avg:55 },
  ],
  activities: [
    { action:'create', type:'Bài học', name:'Everyday Shopping', time:'2 giờ trước' },
    { action:'update', type:'Câu', name:'Airport Check-in #12', time:'4 giờ trước' },
    { action:'publish', type:'Bộ từ', name:'TOEIC Vocab A2', time:'Hôm qua' },
    { action:'delete', type:'Câu', name:'Weather #03 (trùng)', time:'2 ngày trước' },
  ],
  topics: [
    { id:1, name:'Du lịch & Khám phá', slug:'travel', type:'youtube', lessons:12, status:'pub', order:1, updated:'28/09/2026' },
    { id:2, name:'Giao tiếp hàng ngày', slug:'everyday', type:'youtube', lessons:9, status:'pub', order:2, updated:'27/09/2026' },
    { id:3, name:'Công nghệ & AI', slug:'tech', type:'audio', lessons:6, status:'pub', order:3, updated:'25/09/2026' },
    { id:4, name:'Phỏng vấn xin việc', slug:'interview', type:'youtube', lessons:7, status:'pub', order:4, updated:'24/09/2026' },
    { id:5, name:'Ẩm thực & Nhà hàng', slug:'food', type:'video', lessons:5, status:'draft', order:5, updated:'20/09/2026' },
    { id:6, name:'Sức khoẻ & Y tế', slug:'health', type:'mixed', lessons:3, status:'draft', order:6, updated:'18/09/2026' },
  ],
  lessons: [
    { id:1, title:'Ordering Coffee at Starbucks', titleVi:'Gọi cà phê tại Starbucks', topic:'Du lịch', cefr:'A2', src:'YouTube', sents:18, views:312, status:'pub', isPro:false, updated:'28/09/2026' },
    { id:2, title:'Airport Check-in Conversation', titleVi:'Làm thủ tục sân bay', topic:'Du lịch', cefr:'B1', src:'YouTube', sents:24, views:287, status:'pub', isPro:false, updated:'27/09/2026' },
    { id:3, title:'Job Interview: Tell Me About Yourself', titleVi:'Phỏng vấn tự giới thiệu', topic:'Phỏng vấn', cefr:'B2', src:'YouTube', sents:21, views:241, status:'pub', isPro:true, updated:'25/09/2026' },
    { id:4, title:'Talking About the Weather', titleVi:'Nói về thời tiết', topic:'Giao tiếp', cefr:'A1', src:'Audio', sents:14, views:198, status:'pub', isPro:false, updated:'24/09/2026' },
    { id:5, title:'Ordering Food at a Restaurant', titleVi:'Gọi món tại nhà hàng', topic:'Ẩm thực', cefr:'A2', src:'YouTube', sents:20, views:175, status:'pub', isPro:false, updated:'22/09/2026' },
    { id:6, title:'Talking About AI and Technology', titleVi:'Nói về AI và công nghệ', topic:'Công nghệ', cefr:'B2', src:'YouTube', sents:19, views:142, status:'draft', isPro:true, updated:'20/09/2026' },
    { id:7, title:"At the Doctor's Office", titleVi:'Khám bệnh', topic:'Sức khoẻ', cefr:'B1', src:'Audio', sents:16, views:98, status:'draft', isPro:false, updated:'18/09/2026' },
  ],
  decks: [
    { id:1, name:'TOEIC Essential 1000', cat:'TOEIC', cefr:'B1', groups:10, cards:150, isPro:false, status:'pub', updated:'28/09/2026' },
    { id:2, name:'Oxford 3000 — A1', cat:'Oxford', cefr:'A1', groups:5, cards:80, isPro:false, status:'pub', updated:'25/09/2026' },
    { id:3, name:'Business English Advanced', cat:'Giao tiếp', cefr:'C1', groups:8, cards:120, isPro:true, status:'pub', updated:'22/09/2026' },
    { id:4, name:'IELTS Vocabulary', cat:'IELTS', cefr:'B2', groups:12, cards:200, isPro:true, status:'draft', updated:'20/09/2026' },
    { id:5, name:'Daily Conversation Phrases', cat:'Giao tiếp', cefr:'A2', groups:6, cards:90, isPro:false, status:'draft', updated:'18/09/2026' },
  ],
  cefrQueue: [
    { id:1, sent:"Could you please speak a little more slowly?", lesson:'Everyday Conversation', ai:'B1', conf:0.84 },
    { id:2, sent:"The weather has been particularly unpleasant lately.", lesson:'Weather Talk', ai:'B2', conf:0.71 },
    { id:3, sent:"I'd like to make a reservation for two, please.", lesson:'At the Restaurant', ai:'A2', conf:0.92 },
    { id:4, sent:"This technology revolutionises how we interact with machines.", lesson:'Talking About AI', ai:'C1', conf:0.55 },
    { id:5, sent:"I think this is the third time I've been here.", lesson:'Airport Check-in', ai:'B1', conf:0.78 },
    { id:6, sent:"Excuse me, where is the nearest pharmacy?", lesson:"At the Doctor's", ai:'A2', conf:0.91 },
  ],
  reports: [
    { content:'Câu #12 — Airport Check-in', type:'sentence', reason:'Sai bản dịch', desc:'Dịch "gate" thành "cổng" không phù hợp', user:'minhanh_03', date:'29/09/2026', status:'open' },
    { content:'Câu #7 — Weather Talk', type:'sentence', reason:'Lỗi âm thanh', desc:'Đoạn audio bị rè, không nghe rõ', user:'hoangtuan22', date:'28/09/2026', status:'open' },
    { content:'Bộ từ TOEIC Essential', type:'deck', reason:'Sai nội dung', desc:'Thẻ "resilient" có định nghĩa sai', user:'thanhle_b2', date:'27/09/2026', status:'open' },
    { content:'Câu #3 — Job Interview', type:'sentence', reason:'Sai mức CEFR', desc:'Câu này quá khó cho B2', user:'minhchau99', date:'25/09/2026', status:'reviewing' },
    { content:'Câu #18 — Coffee Shop', type:'sentence', reason:'Sai nội dung', desc:'Câu thiếu dấu phẩy', user:'ducphan01', date:'20/09/2026', status:'done' },
  ],
  phonemes: [
    { sym:'/θ/', type:'Phụ âm xát', ex:'think, three, month', desc:'Đặt đầu lưỡi giữa hai hàm răng, thổi hơi.', video:true, isPro:true },
    { sym:'/ð/', type:'Phụ âm xát', ex:'this, that, mother', desc:'Như /θ/ nhưng rung thanh quản.', video:true, isPro:true },
    { sym:'/æ/', type:'Nguyên âm đơn', ex:'cat, hat, man', desc:'Mở miệng rộng, lưỡi xuống thấp.', video:false, isPro:false },
    { sym:'/ɜː/', type:'Nguyên âm đơn', ex:'bird, word, her', desc:'Môi tròn nhẹ, lưỡi giữa.', video:true, isPro:true },
    { sym:'/ŋ/', type:'Phụ âm mũi', ex:'sing, ring, thing', desc:'Đóng miệng, luồng khí qua mũi.', video:false, isPro:false },
    { sym:'/dʒ/', type:'Phụ âm tắc xát', ex:'judge, age, bridge', desc:'Kết hợp /d/ và /ʒ/.', video:false, isPro:false },
  ],
  confusions: [
    { correct:'/θ/', produced:'/t/', group:'Thay phụ âm', tip:'Đặt lưỡi giữa hai hàm răng, không để chạm lợi.' },
    { correct:'/ð/', produced:'/d/', group:'Thay phụ âm', tip:'Rung thanh quản khi lưỡi giữa răng.' },
    { correct:'/æ/', produced:'/a/', group:'Nhầm nguyên âm', tip:'Mở miệng rộng hơn, lưỡi xuống thấp hơn.' },
    { correct:'/l/', produced:'', group:'Rụng âm cuối', tip:'Giữ đầu lưỡi chạm lợi trên đến hết âm.' },
  ],
  minPairs: [
    { phoneA:'/θ/', wordA:'think', phoneB:'/s/', wordB:'sink', pos:'Đầu từ' },
    { phoneA:'/θ/', wordA:'three', phoneB:'/t/', wordB:'tree', pos:'Đầu từ' },
    { phoneA:'/ɪ/', wordA:'ship', phoneB:'/iː/', wordB:'sheep', pos:'Giữa từ' },
    { phoneA:'/l/', wordA:'light', phoneB:'/r/', wordB:'right', pos:'Đầu từ' },
  ],
  qbank: [
    { type:'Từ vựng', content:'resilient', cefr:'C1', attempts:234, knowPct:58, active:true },
    { type:'Từ vựng', content:'abbreviate', cefr:'B2', attempts:189, knowPct:71, active:true },
    { type:'Nghe chép', content:"Could you please speak a little more slowly?", cefr:'B1', attempts:312, knowPct:null, active:true },
    { type:'Nói nhại', content:"I think this is the third time I've been here.", cefr:'B2', attempts:145, knowPct:null, active:true },
    { type:'Từ vựng', content:'ephemeral', cefr:'C1', attempts:98, knowPct:42, active:false },
    { type:'Nghe chép', content:"The weather has been particularly unpleasant lately.", cefr:'B2', attempts:87, knowPct:null, active:true },
  ],
  auditLog: [
    { action:'create', type:'Bài học', name:'Everyday Shopping', time:'29/09/2026 14:32', diff:null },
    { action:'update', type:'Câu', name:'Airport Check-in #12', time:'29/09/2026 11:15', diff:{before:'going throught',after:'going through'} },
    { action:'publish', type:'Bộ từ', name:'TOEIC Essential 1000', time:'28/09/2026 16:00', diff:null },
    { action:'update', type:'Bài học', name:'Ordering Coffee', time:'27/09/2026 09:45', diff:{before:'CEFR: A1',after:'CEFR: A2'} },
    { action:'delete', type:'Câu', name:'Weather Talk #03 (trùng)', time:'26/09/2026 13:20', diff:null },
    { action:'create', type:'Chủ đề', name:'Sức khoẻ & Y tế', time:'25/09/2026 10:00', diff:null },
  ],
  sentences: [
    { id:1, startMs:12300, endMs:15800, text:"I'd like a medium latte, please.", trans:'Tôi muốn một ly latte cỡ vừa.', ipa:'aɪd laɪk ə ˈmiːdiəm ˈlɑːteɪ pleɪz', cefr:'A2', cefrSrc:'instructor' },
    { id:2, startMs:16500, endMs:21200, text:"Could I get that with oat milk?", trans:'Tôi có thể thêm sữa yến mạch được không?', ipa:'kʊd aɪ ɡet ðæt wɪð oʊt mɪlk', cefr:'A2', cefrSrc:'ai', cefrConf:0.89 },
    { id:3, startMs:22000, endMs:27500, text:"Would you like any syrups today?", trans:'Bạn có muốn thêm siro hôm nay không?', ipa:'wʊd juː laɪk ˈeni ˈsɪrəps təˈdeɪ', cefr:'A2', cefrSrc:'reviewed' },
  ],
};
